#!/usr/bin/env python
# Copyright (C) 2021 LEIDOS.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

"""
Subscribe from CARMA :geometry_msgs::PoseStamped
    Topic: /localization/current_pose

Call Services from CARMA:
    Service: /guidance/get_available_routes
             /guidance/set_active_route
"""
import rclpy
from rclpy.node import Node
import time

import rospy
from geometry_msgs.msg import PoseStamped, Pose
from cav_msgs.msg import RouteState, RouteEvent, Route
from cav_srvs.srv import GetAvailableRoutes, SetActiveRoute
from std_msgs.msg import Bool

class CarmaCarlaRoute(Node):

    def __init__(self):
        super().__init__('carma_carla_route')

        self.received_pose = False
        self.is_guidance_bridge_node_active = False

        # Declare and get selected_route
        self.selected_route_id = self.declare_parameter('selected_route', '').get_parameter_value().string_value

        if not self.selected_route_id:
            self.get_logger().error("No input route found. Please check config file at /opt/carma/simulation/vehicle_config.json.")
            rclpy.shutdown()
            return

        time.sleep(2)  # sleep the node for n second to make sure current_pose has been set to CARMA platform properly

        self.available_route_ids = self.get_available_route_ids()
        self.pose_sub = self.create_subscription(PoseStamped, '/localization/current_pose', self.pose_cb, 10)
        self.status_sub = self.create_subscription(Bool, '/carla/guidance_bridge_node/active_status', self.guidance_bridge_node_status_callback, 10)

        self.run_main_loop()

    def pose_cb(self, msg):
        print()

    def guidance_bridge_node_status_callback(self, msg):
        self.is_guidance_bridge_node_active = msg.data
        self.get_logger().info(f"Guidance bridge node status: {msg.data}")

    def get_available_route_ids(self):
        """
        Getting available route function
        if successfully got available route, return available route ID python list
        else, return None
        """
        client = self.create_client(GetAvailableRoutes, '/guidance/get_available_routes')
        if not client.wait_for_service(timeout_sec=10.0):
            self.get_logger().error("/guidance/get_available_routes service not available.")
            return None

        req = GetAvailableRoutes.Request()
        future = client.call_async(req)
        rclpy.spin_until_future_complete(self, future)

        if future.result() is not None:
            route_ids = [route.route_id for route in future.result().available_routes]
            return route_ids
        else:
            self.get_logger().error("Service call to /guidance/get_available_routes failed.")
            return None

    def set_route(self, route_id):
        """
        Set selected route to CARMA platform
        """
        client = self.create_client(SetActiveRoute, '/guidance/set_active_route')
        if not client.wait_for_service(timeout_sec=10.0):
            self.get_logger().error("/guidance/set_active_route service not available.")
            return False

        req = SetActiveRoute.Request()
        req.choice = 0
        req.route_id = route_id

        future = client.call_async(req)
        try:
            rclpy.spin_until_future_complete(self, future)

            if future.result() is not None and not future.result().error_status:
                self.get_logger().info("Call to set_active_route succeeded!")
                return True
            else:
                self.get_logger().error("Error status response from /guidance/set_active_route or empty result.")
                return False
        except:
            self.get_logger().error("Exception occured during the set_active_route call... "
                "Possible that route node's world model is not yet loaded... "
                "Retrying in 1 sec")
        
        return False

    def check_selected_route(self, available_route_ids, selected_route_id):
        """
        Checking if the selected route can be matched with an available route
        """
        matches = [rid for rid in available_route_ids if rid == selected_route_id]
        if len(matches) == 1:
            self.get_logger().info(f"Route found: {selected_route_id}")
            return selected_route_id
        elif len(matches) > 1:
            self.get_logger().error("Duplicate route files found.")
        else:
            self.get_logger().warn(f"Route: {selected_route_id} not found, /guidance/route node could be not ready. "
                      "Otherwise, please check selected_route parameter in carma-config and CARMA route folder (by default: /opt/carma/routes)...")
        return None

    def run_main_loop(self):
        while rclpy.ok():
            if not self.received_pose:
                self.get_logger().info("Localization Incomplete... "
                    "Waiting to receive a pose before attempting to set the Route")
                time.sleep(1)
                continue

            if self.available_route_ids is None:
                self.get_logger().error("No routes available, make sure the route folder at "
                    "/opt/carma/routes has route file")
                time.sleep(1)
                continue

            if (not self.check_selected_route(self.available_route_ids, self.selected_route_id)
                or not self.is_guidance_bridge_node_active):
                # Check again for available routes as sometimes the
                # Route node may not have loaded all the available routes
                self.get_logger().warn(f"Selected route: {self.selected_route_id} "
                    "was not available, retrieving available routes "
                    "again to see if it becomes available")
                self.available_route_ids = self.get_available_route_ids()
                time.sleep(1)
                continue

            time.sleep(2)
            if self.set_route(self.selected_route_id):
                break
            time.sleep(1)

received_pose = False
is_guidance_bridge_node_active = False

def get_available_route_ids():
    """
    Getting available route function
    if successfully got available route, return available route ID python list
    else, return None
    """
    service = rospy.ServiceProxy('/guidance/get_available_routes', GetAvailableRoutes)
    rospy.wait_for_service(service.resolved_name)
    available_route_ids = []
    try:
        resp = service()
        for i in range(len(resp.available_routes)):
            route_msg = resp.available_routes[i]
            available_route_ids.append(resp.available_routes[i].route_id)
        return available_route_ids
    except:
        rospy.logerr("Invalid: /guidance/get_available_routes failed.")

def set_route(selected_route_id):
    """
    Setting selected route to CARMA platform
    """
    service = rospy.ServiceProxy('/guidance/set_active_route', SetActiveRoute)
    rospy.wait_for_service(service.resolved_name)
    try:
        resp = service(choice=0, route_id=selected_route_id)

        if not resp.error_status:
            rospy.loginfo('Call set active route success!')
            return True

        rospy.logerr('Error status response from /guidance/set_active_route:', resp)

    except:
        rospy.logerr("Exception occurs during the set_active_route call... "
            "Possibly route node's world model is not yet loaded... "
            "Retrying in 1 sec")

    return False

def pose_cb(pose_msg):
    """
    callback current_pose to make sure carla_to_carma_localization start to send vehicle position info to CARMA
    PoseStamped message type:
        geometry_msgs::PoseStamped
    """
    global received_pose
    received_pose = True

def check_selected_route(available_route_ids, selected_route_id):
    """
    Checking the selected route if it can be matched with available route
    """
    ind_list = [ind for (ind, route_id) in enumerate(available_route_ids) if route_id == selected_route_id]
    if len(ind_list) == 1:
        rospy.loginfo("Route found!: " + selected_route_id)
        return selected_route_id
    elif len(ind_list) > 1:
        rospy.logerr("Duplicate route files found")
    else:
        rospy.logwarn(f"Route: {selected_route_id} not found, /guidance/route node could be not ready. "
                      "Otherwise, please check selected_route parameter in carma-config and CARMA route folder (by default: /opt/carma/routes)...")
    return None

def guidance_bridge_node_status_callback(data):
    global is_guidance_bridge_node_active
    is_guidance_bridge_node_active = data.data

    rospy.loginfo(f"{rospy.get_caller_id()}: received notice in guidance_bridge_node_status_callback: {data.data}")

def initialize():
    """
    main loop
    """
    rospy.init_node("carma_carla_route")
    selected_route_id = rospy.get_param('~selected_route')
    if selected_route_id == '':
        rospy.logerr("No input route found, please check the config file at /opt/carma/simulation/vehicle_config.json")
        return

    # sleep the node for n second to make sure current_pose has been set to CARMA platform properly
    rospy.sleep(2)
    available_route_ids = get_available_route_ids()
    rospy.Subscriber('/localization/current_pose', PoseStamped, pose_cb)
    rospy.Subscriber('/carla/guidance_bridge_node/active_status', Bool, guidance_bridge_node_status_callback)

    while not rospy.is_shutdown():
        if not received_pose:
            rospy.loginfo("Localization Incomplete... "
                "Waiting to receive a pose before attempting to set the Route")
            rospy.sleep(1)
            continue

        if available_route_ids is None:
            rospy.logerr("No routes available, make sure the route folder at "
                "/opt/carma/routes has route file")
            rospy.sleep(1)
            continue

        if (not check_selected_route(available_route_ids, selected_route_id)
            or not is_guidance_bridge_node_active):
            # Check again for available routes as sometimes the
            # Route node may not have loaded all the available routes
            rospy.logwarn(f"Selected route: {selected_route_id} "
                "was not available, retrieving available routes "
                "again to see if it becomes available")
            available_route_ids = get_available_route_ids()
            rospy.sleep(1)
            continue

        rospy.sleep(2)
        if set_route(selected_route_id):
            break
        rospy.sleep(1)

if __name__ == '__main__':
    rospy.loginfo("carma_carla_route starting")
    initialize()
