#!/usr/bin/env python
# Copyright (C) 2021 LEIDOS.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

"""
Subscribe from CARMA :geometry_msgs::PoseStamped
    Topic: /localization/current_pose

Call Services from CARMA:
    Service: /guidance/get_available_routes
             /guidance/set_active_route
"""

import rospy
from geometry_msgs.msg import PoseStamped, Pose
from cav_msgs.msg import RouteState, RouteEvent, Route
from cav_srvs.srv import GetAvailableRoutes, SetActiveRoute

received_pose = False

def get_available_route_ids():
    """
    Getting available route function
    if successfully got available route, return available route ID python list
    else, return None
    """
    service = rospy.ServiceProxy('/guidance/get_available_routes', GetAvailableRoutes)
    available_route_ids = []
    try:
        resp = service()
        for i in range(len(resp.available_routes)):
            route_msg = resp.available_routes[i]
            available_route_ids.append(resp.available_routes[i].route_id)
        return available_route_ids
    except:
        rospy.logerr("Invalid: /guidance/get_available_routes failed.")
    return None

def set_route(selected_route_id):
    """
    Setting selected route to CARMA platform
    """
    service = rospy.ServiceProxy('/guidance/set_active_route', SetActiveRoute)
    try:
        resp = service(choice=0, route_id=selected_route_id)
        if resp.error_status != 0:
            rospy.logerr('Error status response from /guidance/set_active_route:', resp)
        else:
            rospy.loginfo('Call set active route success!')
    except:
        rospy.logerr("Exception occurs during the set_active_route call")

def pose_cb(pose_msg):
    """
    callback current_pose to make sure carla_to_carma_localization start to send vehicle position info to CARMA
    PoseStamped message type:
        geometry_msgs::PoseStamped
    """
    global received_pose
    received_pose = True

def check_selected_route(available_route_ids, selected_route_id):
    """
    Checking the selected route if it can be matched with available routes.
    """
    if selected_route_id in set(available_route_ids):
        return selected_route_id
    elif available_route_ids.count(selected_route_id) > 1:
        rospy.logerr("Duplicate route files found")
    else:
        rospy.logerr("Cannot match the selected_route input argument with /guidance/get_available_routes {}.".format(selected_route_id))
    return None

def initialize():
    """
    main loop
    """
    rospy.init_node("carma_carla_route")
    selected_route_id = rospy.get_param('~selected_route')
    if selected_route_id == '':
        rospy.logerr("No input route found, please check the config file at /opt/carma/simulation/vehicle_config.json")
        return

    # sleep the node for n second to make sure current_pose has been set to CARMA platform properly
    max_attempts = 10
    available_route_ids = None
    while max_attempts > 0:
        max_attempts = max_attempts - 1
        available_route_ids = get_available_route_ids()
        if available_route_ids is not None:
            break
        rospy.loginfo("{} times to get available from CARMA platform".format(max_attempts))
        rospy.sleep(1)
    if available_route_ids is None:
        rospy.logerr("Falied: Reach maximum times to get available routes, check service /guidance/get_available_routes")
        return
    rospy.Subscriber('/localization/current_pose', PoseStamped, pose_cb)
    while rospy.is_shutdown() != True:
        if received_pose:
            if check_selected_route(available_route_ids, selected_route_id):
                set_route(selected_route_id)
            break
        else:
            rospy.loginfo("Localization Incomplete, waiting for carla_to_carma_localztion launching")
        rospy.sleep(1)

if __name__ == '__main__':
    rospy.loginfo("carma_carla_route")
    initialize()