#!/usr/bin/env python
# Copyright (C) 2023 LEIDOS.
# Migrated to ROS2 under Ryan Fleming @ UGA MSC Lab 2025
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

"""
Subscribe from CARMA :cav_msgs::RouteEvent
    Topic: /guidance/route_event

Call Services from CARMA:
    Service: /guidance/set_guidance_active
             /guidance/plugins/get_active_plugins
"""
import rclpy
from rclpy.node import Node

import ast
import time
import traceback

from cav_msgs.msg import RouteEvent
from cav_msgs.msg import Plugin
from cav_srvs.srv import SetGuidanceActive, PluginList
from std_msgs.msg import Bool

class CarmaCarlaGuidance(Node):
    def __init__(self):
        super().__init__('carma_carla_guidance')

        # Get Parameters
        self.declare_parameter("selected_plugins", "[]")
        self.declare_parameter("start_delay_in_seconds", 15.0)
        plugin_list_str = self.get_parameter("selected_plugins").get_parameter_value().string_value
        self.plugin_list = ast.literal_eval(plugin_list_str)
        self.start_delay = self.get_parameter("start_delay_in_seconds").get_parameter_value().double_value

        if len(self.plugin_list) == 0 or not self.plugin_list:
            self.get_logger().error(
                "No input plugin found. Check the config file at /opt/carma/simulation/vehicle_config.json"
            )
            return
        
         # route selected state
        self.route_selected = False

        # Publishers/Subscribers
        self.status_pub = self.create_publisher(Bool, '/carla/guidance_bridge_node/active_status', 10)
        self.create_subscription(RouteEvent, '/guidance/route_event', self.route_event_callback, 10)

        # CARMA Services
        self.set_guidance_active_client = self.create_client(SetGuidanceActive, '/guidance/set_guidance_active')
        self.get_active_plugins_client = self.create_client(PluginList, '/guidance/plugins/get_active_plugins')

        # Logging
        self.get_logger().info(f"Start delay in seconds: {self.start_delay}")
        self.get_logger().info(f"List of plugins from config: {self.plugin_list}")

        # Wait for required services
        self.get_logger().info('Waiting for services...')
        while not self.get_active_plugins_client.wait_for_service(timeout_sec=1.0):
            self.get_logger().info("waiting for get_active_plugins service...")
        while not self.set_guidance_active_client.wait_for_service(timeout_sec=1.0):
            self.get_logger().info('waiting for set_guidance_active service...')

        # Initially wait for route event callback
        rclpy.spin_once(self, timeout_sec=2.0)

        # Main loop
        while rclpy.ok():
            
            start_time = time.time()
            while time.time() - start_time < 1.5:
                rclpy.spin_once(self, timeout_sec=1.0)
            
            # Publish active status
            status_msg = Bool()
            status_msg.data = True
            self.status_pub.publish(status_msg)

            # Call get_active_plugins service synchronously
            try:
                plugins_request = PluginList.Request()
                plugins_future = self.get_active_plugins_client.call_async(plugins_request)
                rclpy.spin_until_future_complete(self, plugins_future)
            except Exception as e:
                self.get_logger().warn(f"Service call to {self.get_active_plugins_client.srv_name} failed: {e}")
                self.get_logger().warn("Service call can sometimes fail due to ROS, but please make sure the selected plugins are activated. Retrying in 1 second..")
                continue

            active_plugins = plugins_future.result().plugins

            if self.route_selected and self.check_plugin_status(active_plugins):
                if self.engage_guidance():
                    break
            else:
                if not self.route_selected:
                    self.get_logger().debug("Could not engage guidance: route not selected")
                if not self.check_plugin_status(active_plugins):
                    active_names = [plugin.name for plugin in active_plugins]
                    self.get_logger().debug("Could not engage guidance: missing some required plugins")
                    self.get_logger().debug(f"Active plugins: {active_names}")
    
    def engage_guidance(self):
        seconds_passed = 0.0
        while seconds_passed < self.start_delay:
            self.get_logger().info(f"Engaging the guidance in: {self.start_delay - seconds_passed:.0f}")
            seconds_passed += 1.0
            rclpy.spin_once(self, timeout_sec=1.0)

        self.get_logger().info("Attempting to engage guidance")
        try:
            request = SetGuidanceActive.Request()
            request.guidance_active = True
            future = self.set_guidance_active_client.call_async(request)
            rclpy.spin_until_future_complete(self, future)
            if future.result() and future.result().guidance_status:
                self.get_logger().info("Guidance engaged")
                return True
            else:
                self.get_logger().error("Failed to set guidance status, retrying...")
                return False
        except Exception as e:
            self.get_logger().warn(f"Service call to {self.set_guidance_active_client.srv_name} failed: {e}")
            self.get_logger().warn("Service call can sometimes fail due to ROS, but please make sure the platform has started without any error. Retrying in 1 second..")
            return False

    def check_plugin_status(self, active_plugins):
        """
        check active plugin with plugin list
        plugin_list: selected plugins + required plugins
        activate_plugins: the PluginList in /guidance/plugins/get_active_plugins ROS service
        """
        active_names = [p.name for p in active_plugins if p.available and p.activated]
        missing = list(set(self.plugin_list) - set(active_names))
        if len(missing) > 0:
            self.get_logger().warn(f"Some plugins are not activated: {missing}")
            return False
        self.get_logger().info("All plugins activated...!")
        return True
    
    def route_event_callback(self, msg):
        if msg.event == RouteEvent.ROUTE_SELECTED or msg.event == RouteEvent.ROUTE_STARTED:
            # self.get_logger().info("Route Selected")
            self.route_selected = True

def main(args=None):
    rclpy.init(args=args)
    print("carma_carla_guidance")
    try:
        node = CarmaCarlaGuidance()
    except KeyboardInterrupt:
        if node: node.get_logger().info(f"{node.get_name()} shutting down due to KeyboardInterrupt.")
    except Exception as e:
        # Ensure logger is available or use print
        logger = rclpy.logging.get_logger("carma_carla_guidance_main")
        if node : logger = node.get_logger()
        logger.error(f"Unhandled exception in {node.get_name() if node else 'carma_carla_guidance'}: {e}\n{traceback.format_exc()}")
    finally:
        if node:
            node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()

if __name__ == '__main__':
    main()
