name: "CI: Run tests"
on:
  pull_request:
  push:
    paths-ignore:
      - 'PythonAPI/**'
jobs:          
  sonar:
    runs-on: ubuntu-latest
    container:
      image: usdotfhwastoldev/carma-base:develop
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master # Using this GitHub Action, scan your code with SonarCloud to detects bugs, vulnerabilities and code smells in more than 20 programming languages!
        with:
          projectBaseDir: "carma-carla-integration/"
          args: >
            -Dsonar.projectKey=usdot-fhwa-stol_carma-carla-integration
            -Dsonar.python.coverage.reportPaths=./coverage.xml
            -Dsonar.projectName=carma-carla-integration
            -Dsonar.organization=usdot-fhwa-stol
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.verbose=true
            -Dsonar.java.binaries=.
            -Dsonar.c.file.suffixes=-
            -Dsonar.cpp.file.suffixes=-
            -Dsonar.objc.file.suffixes=-
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
